version: '3'
services:
  web:
    container_name: tomcat-web
    build:
      context: ../../
      dockerfile: CA4/part2/web/Dockerfile
    ports:
      - "8080:8080"
    networks:
      default:
        ipv4_address: 192.168.56.10
    depends_on:
      - "db"

  db:
    container_name: h2-database
    build:
      context: ../../
      dockerfile: CA4/part2/db/Dockerfile
    volumes:
      - h2-data:/data
    ports:
      - "8082:8082"
      - "9092:9092"
    networks:
        default:
            ipv4_address: 192.168.56.11

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 192.168.56.0/24

volumes:
  h2-data:
